"""Añadiendo tabla de incidencias

Revision ID: 0a65b3bf8059
Revises: 41ed816708a7
Create Date: 2026-01-24 11:28:36.964069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a65b3bf8059'
down_revision = '41ed816708a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidencia',
    sa.Column('id_incidencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('comentario_trabajador', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('comentario_admin', sa.Text(), nullable=True),
    sa.Column('id_trabajador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_trabajador'], ['trabajador.id_trabajador'], ),
    sa.PrimaryKeyConstraint('id_incidencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidencia')
    # ### end Alembic commands ###
