"""Inicializar BBDD completa

Revision ID: 41ed816708a7
Revises: 
Create Date: 2026-01-22 20:27:41.808509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ed816708a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombrecomercial', sa.String(length=120), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('radio', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('horario',
    sa.Column('id_horario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_horario', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_rol', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('franjas',
    sa.Column('id_dia', sa.Integer(), nullable=False),
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_dia'], ['dia.id'], ),
    sa.ForeignKeyConstraint(['id_horario'], ['horario.id_horario'], ),
    sa.PrimaryKeyConstraint('id_dia', 'id_horario')
    )
    op.create_table('trabajador',
    sa.Column('id_trabajador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('passw', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telef', sa.String(length=30), nullable=True),
    sa.Column('idEmpresa', sa.Integer(), nullable=False),
    sa.Column('idHorario', sa.Integer(), nullable=False),
    sa.Column('idRol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['idHorario'], ['horario.id_horario'], ),
    sa.ForeignKeyConstraint(['idRol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_trabajador')
    )
    op.create_table('fichaje',
    sa.Column('id_fichaje', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('id_trabajador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_trabajador'], ['trabajador.id_trabajador'], ),
    sa.PrimaryKeyConstraint('id_fichaje')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fichaje')
    op.drop_table('trabajador')
    op.drop_table('franjas')
    op.drop_table('rol')
    op.drop_table('horario')
    op.drop_table('empresa')
    op.drop_table('dia')
    # ### end Alembic commands ###
